### ISSUE TITLE
Unimplemented

### ISSUE THREAD

**Issue by rgleason** [nohal/nsk_pi#11]
![1-nsk](https://user-images.githubusercontent.com/2363959/225658119-c57d7278-3f53-43bc-ab1a-8cac441714ce.png)

This is not available.    Missing DATA

![image](https://user-images.githubusercontent.com/2363959/225657961-0316e4ac-c9d1-4a06-86c5-8630e234e5d7.png)

**Comment by nohal** [comment]
Could you please elaborate on what you mean?

**Comment by rgleason** [comment]
No selections.  I believe the data directory does not exist.

![1-nsk-2](https://user-images.githubusercontent.com/2363959/225660209-4e16248a-86a8-49c1-ab2d-f31c9528f249.png)

  I believe the data directory does not exist.  Actually I am wrong, there is an icon and a json file.
C:\Users\fcgle\AppData\Local\opencpn\plugins\NSK_pi\data

![image](https://user-images.githubusercontent.com/2363959/225660773-1f29a62d-72cd-4fd2-8937-902b51116990.png)
![data-dir](https://user-images.githubusercontent.com/2363959/225661294-c1a2dcc2-62fd-4c4b-bfd5-952e49d06187.png)

**Comment by rgleason** [comment]
Of course,  So obvious.
![nsk-running](https://user-images.githubusercontent.com/2363959/225690353-3aa423df-c5d1-473e-ab06-73957ff30b03.png)

Now what?   Do I have to select something?
How do I get sk into DashboardSK now?

**Comment by nohal** [comment]
You already have it there, nothing else needs to be done. Just create your dashboards.

**Comment by rgleason** [comment]
Ok trying HDGtrue.  - Don't pick just HeadingTrue (it just yields "0.0" value, which heading true exactly, from what NMEA sentence?   

![HDGtrue](https://user-images.githubusercontent.com/2363959/225704681-ca2e7572-0f09-4ebc-88a9-ef04c67331d6.png)


![HDGtrue-5](https://user-images.githubusercontent.com/2363959/225704399-d92ebe7a-d5f1-4499-b8cf-de93c277776c.png)

![HDGtrue-4](https://user-images.githubusercontent.com/2363959/225704416-289df928-c4ae-4d35-ba78-78c8443d1aed.png)

![HDGtrue-3](https://user-images.githubusercontent.com/2363959/225704442-14564e47-0119-4322-a4c8-4d028039f1d4.png)

![HDGtrue-2](https://user-images.githubusercontent.com/2363959/225704468-27040639-123d-4035-a9f4-ccfa9e92a3b4.png)

![HDGtrue-1](https://user-images.githubusercontent.com/2363959/225704480-1100b8a6-4293-47e4-8e9e-2f5b8db620b7.png)

![HDGtrue](https://user-images.githubusercontent.com/2363959/225704538-c69ce9c7-6188-4db4-b114-11ae1a16da27.png)

**Comment by nohal** [comment]
Rick... I have absolutely no idea what is in your data stream. Connect to `signalk.stupan.se` and we can talk about that.

**Comment by nohal** [comment]
Anyway, if you struggle with DashboardSK, it is a completely different plugin and out of scope of this issue, which I suppose is now resolved for you.

**Comment by rgleason** [comment]
Pavel, just showing that I got it working!!!  Thanks.
I was using a nmea text file from  Hartmut.
